line-length = 100
target-version = "py312"

[lint]
select = ["E", "F", "W", "I", "UP", "B", "ASYNC"]
ignore = ["E501", "B008", "UP006", "UP007", "UP035", "UP037"]

[lint.isort]
known-first-party = ["app"]
